.TH   "pytimechart" "1"
.SH NAME
pytimechart \- Fast graphical exploration and visualisation for linux kernel traces
.SH Usage
.sp
pytimechart [trace.txt|trace.txt.gz|trace.txt.lzma|trace.dat]
.sp
pyTimechart is aimed at helping kernel developer to browse into large scale traces.
.sp
See <\fI\%http://packages.python.org/pytimechart/\fP> for more information and documentation
.
